//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Price
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soa.btgpactual.com/EntityServices/Price/RequestReply/v1", ConfigurationName="Price.GetPrice")]
    public interface GetPrice
    {
        
        // CODEGEN: Generating message contract since the operation GetPrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/GetPriceService/GetPrice", ReplyAction="http://www.example.org/GetPriceService/GetPriceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Price.GetPriceResponse GetPrice(Price.GetPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/GetPriceService/GetPrice", ReplyAction="http://www.example.org/GetPriceService/GetPriceResponse")]
        System.Threading.Tasks.Task<Price.GetPriceResponse> GetPriceAsync(Price.GetPriceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/TSM/AssetPricing/AssetPricing1/Query/GetPrice/Requ" +
        "est/v1")]
    public partial class Request
    {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private AssetPricingDetail[] assetPricingDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssetPricingDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AssetPricingDetail[] AssetPricingDetails
        {
            get
            {
                return this.assetPricingDetailsField;
            }
            set
            {
                this.assetPricingDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/TSM/AssetPricing/AssetPricing1/Query/GetPrice/Requ" +
        "est/v1")]
    public partial class AssetPricingDetail
    {
        
        private int codAtivoField;
        
        private string priceTypeField;
        
        private PriceFactTypeCode priceFactTypeField;
        
        private bool ajustedValueField;
        
        private bool ajustedValueFieldSpecified;
        
        private bool repeatedValueField;
        
        private bool repeatedValueFieldSpecified;
        
        private string marketField;
        
        private string feederField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int CodAtivo
        {
            get
            {
                return this.codAtivoField;
            }
            set
            {
                this.codAtivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PriceType
        {
            get
            {
                return this.priceTypeField;
            }
            set
            {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PriceFactTypeCode PriceFactType
        {
            get
            {
                return this.priceFactTypeField;
            }
            set
            {
                this.priceFactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool AjustedValue
        {
            get
            {
                return this.ajustedValueField;
            }
            set
            {
                this.ajustedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AjustedValueSpecified
        {
            get
            {
                return this.ajustedValueFieldSpecified;
            }
            set
            {
                this.ajustedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool RepeatedValue
        {
            get
            {
                return this.repeatedValueField;
            }
            set
            {
                this.repeatedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepeatedValueSpecified
        {
            get
            {
                return this.repeatedValueFieldSpecified;
            }
            set
            {
                this.repeatedValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Market
        {
            get
            {
                return this.marketField;
            }
            set
            {
                this.marketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Feeder
        {
            get
            {
                return this.feederField;
            }
            set
            {
                this.feederField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/TSM/AssetPricing/AssetPricing1/Query/GetPrice/Requ" +
        "est/v1")]
    public enum PriceFactTypeCode
    {
        
        /// <remarks/>
        LAST,
        
        /// <remarks/>
        CLOS,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        LOOW,
        
        /// <remarks/>
        OPEN,
        
        /// <remarks/>
        BEST,
        
        /// <remarks/>
        AVER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class Feeder
    {
        
        private string identificationField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class Market
    {
        
        private string defaultCurrencyField;
        
        private string identificationField;
        
        private string tradingCurrencyField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DefaultCurrency
        {
            get
            {
                return this.defaultCurrencyField;
            }
            set
            {
                this.defaultCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TradingCurrency
        {
            get
            {
                return this.tradingCurrencyField;
            }
            set
            {
                this.tradingCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class CurrencyAndAmount
    {
        
        private string currencyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class AssetIdentification
    {
        
        private int codAtivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int CodAtivo
        {
            get
            {
                return this.codAtivoField;
            }
            set
            {
                this.codAtivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class Asset
    {
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private System.DateTime maturityDateField;
        
        private bool maturityDateFieldSpecified;
        
        private AssetIdentification assetIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime MaturityDate
        {
            get
            {
                return this.maturityDateField;
            }
            set
            {
                this.maturityDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaturityDateSpecified
        {
            get
            {
                return this.maturityDateFieldSpecified;
            }
            set
            {
                this.maturityDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AssetIdentification AssetIdentification
        {
            get
            {
                return this.assetIdentificationField;
            }
            set
            {
                this.assetIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class AssetPricing
    {
        
        private Asset assetField;
        
        private System.DateTime dateField;
        
        private bool estimatedPriceIndicatorField;
        
        private bool estimatedPriceIndicatorFieldSpecified;
        
        private CurrencyAndAmount priceField;
        
        private PriceFactTypeCode1 priceFactTypeField;
        
        private string priceTypeField;
        
        private Market marketIdentificationField;
        
        private Feeder priceIssuerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Asset Asset
        {
            get
            {
                return this.assetField;
            }
            set
            {
                this.assetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool EstimatedPriceIndicator
        {
            get
            {
                return this.estimatedPriceIndicatorField;
            }
            set
            {
                this.estimatedPriceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedPriceIndicatorSpecified
        {
            get
            {
                return this.estimatedPriceIndicatorFieldSpecified;
            }
            set
            {
                this.estimatedPriceIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CurrencyAndAmount Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public PriceFactTypeCode1 PriceFactType
        {
            get
            {
                return this.priceFactTypeField;
            }
            set
            {
                this.priceFactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PriceType
        {
            get
            {
                return this.priceTypeField;
            }
            set
            {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Market MarketIdentification
        {
            get
            {
                return this.marketIdentificationField;
            }
            set
            {
                this.marketIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Feeder PriceIssuer
        {
            get
            {
                return this.priceIssuerField;
            }
            set
            {
                this.priceIssuerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PriceFactTypeCode", Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public enum PriceFactTypeCode1
    {
        
        /// <remarks/>
        LAST,
        
        /// <remarks/>
        CLOS,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        LOOW,
        
        /// <remarks/>
        OPEN,
        
        /// <remarks/>
        BEST,
        
        /// <remarks/>
        AVER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
        "onse/v1")]
    public partial class Response
    {
        
        private AssetPricing assetPricingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AssetPricing AssetPricing
        {
            get
            {
                return this.assetPricingField;
            }
            set
            {
                this.assetPricingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceRequest", Namespace="http://soa.btgpactual.com/BTGP/TSM/AssetPricing/AssetPricing1/Query/GetPrice/Requ" +
            "est/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Price.Request[] GetPriceRequest1;
        
        public GetPriceRequest()
        {
        }
        
        public GetPriceRequest(Price.Request[] GetPriceRequest1)
        {
            this.GetPriceRequest1 = GetPriceRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceResponse", Namespace="http://soa.btgpactual.com/BTGP/ESM/AssetPricing/AssetPricing1/Query/GetPrice/Resp" +
            "onse/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Price.Response[] GetPriceResponse1;
        
        public GetPriceResponse()
        {
        }
        
        public GetPriceResponse(Price.Response[] GetPriceResponse1)
        {
            this.GetPriceResponse1 = GetPriceResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetPriceChannel : Price.GetPrice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetPriceClient : System.ServiceModel.ClientBase<Price.GetPrice>, Price.GetPrice
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetPriceClient() : 
                base(GetPriceClient.GetDefaultBinding(), GetPriceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GetPriceServiceSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPriceClient(EndpointConfiguration endpointConfiguration) : 
                base(GetPriceClient.GetBindingForEndpoint(endpointConfiguration), GetPriceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPriceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetPriceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPriceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetPriceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPriceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Price.GetPriceResponse Price.GetPrice.GetPrice(Price.GetPriceRequest request)
        {
            return base.Channel.GetPrice(request);
        }
        
        public Price.Response[] GetPrice(Price.Request[] GetPriceRequest1)
        {
            Price.GetPriceRequest inValue = new Price.GetPriceRequest();
            inValue.GetPriceRequest1 = GetPriceRequest1;
            Price.GetPriceResponse retVal = ((Price.GetPrice)(this)).GetPrice(inValue);
            return retVal.GetPriceResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Price.GetPriceResponse> Price.GetPrice.GetPriceAsync(Price.GetPriceRequest request)
        {
            return base.Channel.GetPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Price.GetPriceResponse> GetPriceAsync(Price.Request[] GetPriceRequest1)
        {
            Price.GetPriceRequest inValue = new Price.GetPriceRequest();
            inValue.GetPriceRequest1 = GetPriceRequest1;
            return ((Price.GetPrice)(this)).GetPriceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetPriceServiceSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetPriceServiceSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://nsap370pafh.pactual.net/EDM/Price/GetPriceService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetPriceClient.GetBindingForEndpoint(EndpointConfiguration.GetPriceServiceSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetPriceClient.GetEndpointAddress(EndpointConfiguration.GetPriceServiceSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            GetPriceServiceSOAP,
        }
    }
}
